# workflow 名称
name: schedule-mirror

# 创建定时任务
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# 需要执行的任务列表
jobs:
  # 镜像转换任务
  mirror_transition: 
    # 运行环境
    runs-on: ubuntu-latest
    # 镜像转换任务的步骤列表
    steps:
      # 1. 切换分支（默认主分支）
      - name: Check out code
        uses: actions/checkout@v2
      # 2. 设置 go 环境
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      # 3. 运行 go 代码
      - name: Run code
        run: go run schedule.go --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_TOKEN }} --repository=${{ secrets.DOCKER_REPOSITORY }} --content='{"schedule-mirror":["ghcr.io/imagegenius/immich"]}' --maxContent=11 --outputPath=output.sh
      - name: echo
        run: echo "Finished!"
